remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

title: "Yuyao's Notebook"
title_separator: "-"
name: "Yuyao Wang"
description: "A blog about data, code, and life."
locale: "en-US"
url: "https://olivia3395.github.io"
baseurl: ""
repository: "olivia3395/olivia3395.github.io"
logo: "/assets/images/bio-photo.jpg"
masthead_title: "Yuyao Wang"

author:
  name: "Yuyao Wang"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Ph.D. student in Statistics @ Boston University. Exploring transfer learning, graph mining, and theoretical ML."
  location: "Boston, MA"
  email: "yuyaow@bu.edu"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/olivia3395"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yuyao-w-990571191/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yuyaow@bu.edu"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/olivia3395"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yuyao-w-990571191/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yuyaow@bu.edu"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: "America/New_York"
paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

search: true
search_provider: lunr
